/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZoneMapRouteImport } from './routes/zone-map'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaveRouteImport } from './routes/leave'
import { Route as GrievancesRouteImport } from './routes/grievances'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as EmployeeSetupRouteImport } from './routes/employee-setup'
import { Route as Employee360RouteImport } from './routes/employee-360'
import { Route as DelhiWorkforceRouteImport } from './routes/delhi-workforce'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as IndexRouteImport } from './routes/index'

const ZoneMapRoute = ZoneMapRouteImport.update({
  id: '/zone-map',
  path: '/zone-map',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRoute = LeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const GrievancesRoute = GrievancesRouteImport.update({
  id: '/grievances',
  path: '/grievances',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeSetupRoute = EmployeeSetupRouteImport.update({
  id: '/employee-setup',
  path: '/employee-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const Employee360Route = Employee360RouteImport.update({
  id: '/employee-360',
  path: '/employee-360',
  getParentRoute: () => rootRouteImport,
} as any)
const DelhiWorkforceRoute = DelhiWorkforceRouteImport.update({
  id: '/delhi-workforce',
  path: '/delhi-workforce',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/dashboard': typeof DashboardRoute
  '/delhi-workforce': typeof DelhiWorkforceRoute
  '/employee-360': typeof Employee360Route
  '/employee-setup': typeof EmployeeSetupRoute
  '/employees': typeof EmployeesRoute
  '/grievances': typeof GrievancesRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/payroll': typeof PayrollRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/transfers': typeof TransfersRoute
  '/zone-map': typeof ZoneMapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/dashboard': typeof DashboardRoute
  '/delhi-workforce': typeof DelhiWorkforceRoute
  '/employee-360': typeof Employee360Route
  '/employee-setup': typeof EmployeeSetupRoute
  '/employees': typeof EmployeesRoute
  '/grievances': typeof GrievancesRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/payroll': typeof PayrollRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/transfers': typeof TransfersRoute
  '/zone-map': typeof ZoneMapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/dashboard': typeof DashboardRoute
  '/delhi-workforce': typeof DelhiWorkforceRoute
  '/employee-360': typeof Employee360Route
  '/employee-setup': typeof EmployeeSetupRoute
  '/employees': typeof EmployeesRoute
  '/grievances': typeof GrievancesRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/payroll': typeof PayrollRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/transfers': typeof TransfersRoute
  '/zone-map': typeof ZoneMapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/dashboard'
    | '/delhi-workforce'
    | '/employee-360'
    | '/employee-setup'
    | '/employees'
    | '/grievances'
    | '/leave'
    | '/login'
    | '/payroll'
    | '/profile'
    | '/settings'
    | '/transfers'
    | '/zone-map'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/dashboard'
    | '/delhi-workforce'
    | '/employee-360'
    | '/employee-setup'
    | '/employees'
    | '/grievances'
    | '/leave'
    | '/login'
    | '/payroll'
    | '/profile'
    | '/settings'
    | '/transfers'
    | '/zone-map'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/dashboard'
    | '/delhi-workforce'
    | '/employee-360'
    | '/employee-setup'
    | '/employees'
    | '/grievances'
    | '/leave'
    | '/login'
    | '/payroll'
    | '/profile'
    | '/settings'
    | '/transfers'
    | '/zone-map'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  DashboardRoute: typeof DashboardRoute
  DelhiWorkforceRoute: typeof DelhiWorkforceRoute
  Employee360Route: typeof Employee360Route
  EmployeeSetupRoute: typeof EmployeeSetupRoute
  EmployeesRoute: typeof EmployeesRoute
  GrievancesRoute: typeof GrievancesRoute
  LeaveRoute: typeof LeaveRoute
  LoginRoute: typeof LoginRoute
  PayrollRoute: typeof PayrollRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  TransfersRoute: typeof TransfersRoute
  ZoneMapRoute: typeof ZoneMapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zone-map': {
      id: '/zone-map'
      path: '/zone-map'
      fullPath: '/zone-map'
      preLoaderRoute: typeof ZoneMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave': {
      id: '/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grievances': {
      id: '/grievances'
      path: '/grievances'
      fullPath: '/grievances'
      preLoaderRoute: typeof GrievancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-setup': {
      id: '/employee-setup'
      path: '/employee-setup'
      fullPath: '/employee-setup'
      preLoaderRoute: typeof EmployeeSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-360': {
      id: '/employee-360'
      path: '/employee-360'
      fullPath: '/employee-360'
      preLoaderRoute: typeof Employee360RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delhi-workforce': {
      id: '/delhi-workforce'
      path: '/delhi-workforce'
      fullPath: '/delhi-workforce'
      preLoaderRoute: typeof DelhiWorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  DashboardRoute: DashboardRoute,
  DelhiWorkforceRoute: DelhiWorkforceRoute,
  Employee360Route: Employee360Route,
  EmployeeSetupRoute: EmployeeSetupRoute,
  EmployeesRoute: EmployeesRoute,
  GrievancesRoute: GrievancesRoute,
  LeaveRoute: LeaveRoute,
  LoginRoute: LoginRoute,
  PayrollRoute: PayrollRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  TransfersRoute: TransfersRoute,
  ZoneMapRoute: ZoneMapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
